# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: testdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
pipelines:
  pull-requests:
    '**': # This runs as default for any branch not elsewhere defined.
      - step:
          services:
            - postgres
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm test
  branches:
    master:
      - step:
          services:
            - postgres
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm test
  tags:
    v*:
      - step:
          name: Build and deploy
          services:
            - postgres
            - docker
          caches:
            - node
          script:
            - npm install
            - npm test
            - ./deploy.sh
