version: '3.9'
services:
    kidsloop-user-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: user-service
        environment:
            - DOMAIN=kidsloop-user-service:8080
            - DATABASE_URL=postgres://postgres:kidsloop@postgres1:5432/postgres1
            - STORAGE_BUCKET=kidsloop-alpha-account-asset-objects
            - STORAGE_PROVIDER=amazon
            - NODE_ENV=development
            - FORCE_LOCAL_STORAGE=true
            - STORAGE_ENDPOINT=http://localstack1:4566
            - STORAGE_ACCESS_KEY_ID=""
            - STORAGE_SECRET_ACCESS_KEY=""
            - STORAGE_REGION=eu-west-1
            - ROUTE_PREFIX=/user
            - USER_SERVICE_API_KEY=test-api-token
        expose:
            - '8080'
        ports:
            - '8080:8080'
        depends_on:
            - postgres1
            - localstack1
        volumes:
            # for exposing coverage results collected inside the container
            - ./.nyc_output:/usr/src/app/.nyc_output
            # for putting coverage instrumented code into the container
            - ./dist/src:/usr/src/app/src
    postgres1:
        container_name: postgres1
        image: postgres:11.9
        restart: always
        environment:
            - POSTGRES_DB=postgres1
            - POSTGRES_PASSWORD=kidsloop
        ports:
            - 5432:5432
    localstack1:
        container_name: localstack1
        image: localstack/localstack:0.12.12
        restart: always
        environment:
            - SERVICES=s3
        ports:
            - 4566:4566
        volumes:
            - ./scripts:/docker-entrypoint-initaws.d
